config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'pages#landing'

  get 'about', to: 'pages#about', as: :about
  get 'tos', to: 'pages#tos', as: :tos

  get 'badness/:secret', to: 'pages#badness'

  direct :git_head do
    "https://github.com/Gamocosm/Gamocosm/tree/#{Gamocosm::GIT_HEAD}"
  end

  direct :blog do
    'https://gamocosm.com/blog/'
  end

  direct :wiki do |page|
    if page.blank?
      'https://github.com/Gamocosm/Gamocosm/wiki'
    else
      "https://github.com/Gamocosm/Gamocosm/wiki/#{page}"
    end
  end

  direct :issues do
    'https://github.com/Gamocosm/Gamocosm/issues'
  end

  direct :source do
    'https://github.com/Gamocosm/Gamocosm'
  end

  direct :license do
    'https://github.com/Gamocosm/Gamocosm/blob/master/LICENSE'
  end

  direct :cuberite_website do
    'https://cuberite.org'
  end

  direct :gitter_lobby do
    'https://gitter.im/gamocosm/Lobby'
  end

  direct :digital_ocean_control_panel do
    'https://cloud.digitalocean.com'
  end

  direct :digital_ocean_status do
    'https://status.digitalocean.com'
  end

  direct :digital_ocean_api_setup do
    'https://docs.digitalocean.com/reference/api/create-personal-access-token/'
  end

  namespace :digital_ocean do
    resources :droplets, only: [:index, :destroy]

    resources :images, only: [:index, :destroy]

    resources :ssh_keys, only: [:index, :create, :destroy]

    resources :volumes, only: [:index, :destroy]

    resources :snapshots, only: [:index, :destroy]

    delete 'cache', to: '/servers#refresh_digital_ocean_cache', as: :refresh_cache
  end

  get 'servers/new', to: 'servers#new', as: :new_server
  post 'servers/new', to: 'servers#create', as: nil
  resources :servers, only: [:index, :show, :update, :destroy] do
    member do
      get 'confirm_delete'

      post 'start'
      post 'stop'
      post 'reboot'

      post 'pause'
      post 'resume'
      post 'command'
      post 'backup'
      get 'download'

      put 'update_properties'

      post 'add_friend'
      post 'remove_friend'

      post 'autoshutdown_enable'
      post 'autoshutdown_disable'

      delete 'clear_logs'

      scope path: 'api/:key', as: :api, controller: :api do
        get 'status'
        post 'start'
        post 'stop'
        post 'reboot'
        post 'pause'
        post 'resume'
        post 'backup'
        post 'exec'
      end
    end
  end

  resources :volumes, only: [:index, :new, :show, :edit, :create, :update, :destroy] do
    member do
      get 'confirm_delete'
      post 'suspend'
      post 'reload'
    end
  end

  devise_for :users, controllers: { registrations: :registrations }

  if Rails.env.production?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV['SIDEKIQ_USERNAME'])) &
        ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV['SIDEKIQ_PASSWORD']))
    end
  end
  mount Sidekiq::Web => '/sidekiq'

  match '*unused', to: 'pages#not_found', via: :all

end

app/models/minecraft.rb
# == Schema Information
#
# Table name: minecrafts
#
#  id                           :bigint           not null, primary key
#  created_at                   :datetime
#  updated_at                   :datetime
#  server_id                    :uuid             not null
#  flavour                      :string           not null
#  mcsw_password                :string           not null
#  autoshutdown_enabled         :boolean          default(FALSE), not null
#  autoshutdown_last_check      :datetime         not null
#  autoshutdown_last_successful :datetime         not null
#  autoshutdown_minutes         :integer          default(8), not null
#

class Minecraft < ActiveRecord::Base
  belongs_to :server

  validates :autoshutdown_minutes, numericality: { only_integer: true, greater_than_or_equal_to: 5, less_than: 24 * 60 }

  after_initialize :after_initialize_callback
  before_validation :before_validate_callback

  def after_initialize_callback
    self.autoshutdown_last_check ||= Time.now
    self.autoshutdown_last_successful ||= Time.now
    self.mcsw_password ||= SecureRandom.hex(16)
  end

  def before_validate_callback
    if self.new_record?
      if !Gamocosm::MINECRAFT_FLAVOURS.has_key?(self.flavour)
        self.errors.add(:flavour, 'Invalid flavour')
      end
    end
  end

  def flavour_info
    Gamocosm::MINECRAFT_FLAVOURS[self.flavour]
  end

  def node
    if @node.nil?
      if server.running?
        @node = Minecraft::Node.new(self, server.remote.ip_address)
      end
    end
    @node
  end

  def properties
    if @properties.nil?
      if server.running?
        response = node.properties
        if response.error?
          server.log("Error getting Minecraft properties: #{response}")
          @properties = response
        else
          @properties = Minecraft::Properties.new(response)
        end
      end
    end
    @properties
  end

  def world_download_url
    if server.running?
      return "http://#{Gamocosm::MCSW_USERNAME}:#{mcsw_password}@#{server.remote.ip_address}:#{Minecraft::Node::MCSW_PORT}/download_world"
    end
    nil
  end

  def running?
    server.running? && !node.error? && node.pid > 0
  end

  def resume
    error = resume?
    if error
      return error
    end
    node.resume
  end

  def pause
    error = pause?
    if error
      if server.running? && !node.error? && !(node.pid > 0)
        return nil
      end
      return error
    end
    node.pause
  end

  def exec(current_user, command)
    error = exec?(current_user)
    if error
      return error
    end
    node.exec(command)
  end

  def backup
    error = backup?
    if error
      return error
    end
    node.backup
  end

  def resume?
    if !server.running?
      return 'Server not running'
    end
    if node.error?
      return node.pid
    end
    if node.pid > 0
      return 'Minecraft already running'
    end
    nil
  end

  def pause?
    if !server.running?
      return 'Server not running'
    end
    if node.error?
      return node.pid
    end
    if !(node.pid > 0)
      return 'Minecraft not running'
    end
    nil
  end

  def exec?(current_user)
    if !server.owner?(current_user)
      return 'Only the server owner can execute commands'
    end
    # the next three are the same as !running?
    if !server.running?
      return 'Server not running'
    end
    if node.error?
      return node.pid
    end
    if !(node.pid > 0)
      return 'Minecraft not running'
    end
    nil
  end

  def backup?
    if !server.running?
      return 'Server not running'
    end
    if node.error?
      return node.pid
    end
    if node.pid > 0
      return 'Minecraft is running'
    end
    nil
  end

  def download?
    backup?
  end
end

app/models/minecraft/node.rb
class Minecraft::Node
  MCSW_PORT = 5000
  HTTP_REQUEST_TIMEOUT = 4

  def initialize(local_minecraft, ip_address)
    @local_minecraft = local_minecraft
    @ip_address = ip_address
    @port = MCSW_PORT
    @conn = Faraday.new(url: "http://#{@ip_address}:#{@port}") do |conn|
      conn.request :basic_auth, Gamocosm::MCSW_USERNAME, @local_minecraft.mcsw_password
      conn.response :json
      conn.adapter Faraday.default_adapter
    end
  end

  def invalidate
    @pid = nil
  end

  def error?
    pid.error?
  end

  def num_players
    errors = []
    if @querier_status.nil?
      @querier_status = Minecraft::Ping.new(@ip_address)
    end
    n = @querier_status.players_online
    if !n.error?
      return n
    end
    errors.push(n)
    if @querier.nil?
      @querier = Minecraft::Querier.new(@ip_address)
    end
    n = @querier.read_num_players
    if !n.error?
      return n
    end
    errors.push(n)
    "Could not query Minecraft: #{errors}".error!(errors)
  end

  def pid
    silence do
      if @pid.nil?
        res = do_get(:pid)
        if res.error?
          @pid = res
          @local_minecraft.server.log("Error getting Minecraft pid: #{res}")
        else
          @pid = res['pid']
        end
      end
      return @pid
    end
  end

  def resume
    silence do
      res = do_post(:start, { ram: "#{@local_minecraft.server.ram}M" })
      invalidate
      if res.error?
        return res
      end
      return nil
    end
  end

  def pause
    silence do
      res = do_post(:stop, {}, 32)
      invalidate
      if res.error?
        return res
      end
      return nil
    end
  end

  def exec(command)
    silence do
      res = do_post(:exec, { command: })
      if res.error?
        return res
      end
      return nil
    end
  end

  def backup
    silence do
      res = do_post(:backup, {})
      if res.error?
        return res
      end
      return nil
    end
  end

  def properties
    silence do
      res = do_get(:minecraft_properties)
      if res.error?
        return res
      end
      return res['properties']
    end
  end

  def update_properties(properties)
    silence do
      payload = {}
      properties.each_pair do |k, v|
        payload[k.to_s.gsub('_', '-')] = v.to_s
      end
      res = do_post(:minecraft_properties, { properties: payload })
      if res.error?
        return res
      end
      return res['properties']
    end
  end

  private
  def do_get(endpoint)
    begin
      res = @conn.get do |req|
        req.url "/#{endpoint}"
        req.options.open_timeout = HTTP_REQUEST_TIMEOUT
        req.options.timeout = HTTP_REQUEST_TIMEOUT
      end
      parse_response(res, endpoint)
    rescue Faraday::Error => e
      msg = "MCSW API network exception: #{e}"
      Rails.logger.error msg
      Rails.logger.error e.backtrace.join("\n")
      msg.error! e
    end
  end

  def do_post(endpoint, data, timeout = HTTP_REQUEST_TIMEOUT)
    begin
      res = @conn.post do |req|
        req.url "/#{endpoint}"
        req.options.open_timeout = timeout
        req.options.timeout = timeout
        req.headers['Content-Type'] = 'application/json'
        req.body = data.to_json
      end
      parse_response(res, endpoint)
    rescue Faraday::Error => e
      msg = "MCSW API network exception: #{e}"
      Rails.logger.error msg
      Rails.logger.error e.backtrace.join("\n")
      msg.error! e
    end
  end

  def parse_response(res, endpoint)
    if res.status != 200
      msg = "MCSW API error: HTTP response code #{res.status}, #{res.body}"
      return msg.error! res
    end
    if !res.body['status'].nil?
      msg = "MCSW API error: action #{endpoint} response status not OK, was #{res.body['status']}, #{res.body}"
      return msg.error! res
    end
    res.body
  end
end

app/models/minecraft/ping.rb
class Minecraft::Ping
  VERSION = 0
  TIMEOUT = 1

  def initialize(ip_address, port = 25_565)
    @ip_address = ip_address
    @port = port
    self.reset(nil)
  end

  def reset(con)
    @con = con
    @buf = ''.ascii
    @pos = 0
    @token = Random.rand(256)
  end

  def create_varint(x)
    buf = []
    for _ in 0...5
      if x & ~0x7f == 0
        buf.push(x)
        return buf.pack('C*').ascii
      end
      buf.push((x & 0x7f) | 0x80)
      x >>= 7
    end
    raise "#{self.class.name} sending varint too big: #{x}"
  end

  def create_string(str)
    utf8 = str.encode('utf-8')
    self.create_varint(utf8.bytesize) + utf8.ascii
  end

  def create_short(x)
    [x].pack('S>').ascii
  end

  def create_long(x)
    [x].pack('q>').ascii
  end

  def create_packet(id, buf)
    data = self.create_varint(id) + buf
    self.create_varint(data.bytesize) + data
  end

  def handshake
    buf = self.create_varint(VERSION)
    buf += self.create_string(@ip_address)
    buf += self.create_short(@port)
    buf += self.create_varint(1)
    packet = self.create_packet(0, buf)
    self.send(packet)
  end

  def ping
    buf = self.create_long(@token)
    packet = self.create_packet(1, buf)
    self.send(packet)
  end

  def status
    buf = ''.ascii
    packet = self.create_packet(0, buf)
    self.send(packet)
  end

  def read
    data = self.recv(1024)
    if data.encoding != @buf.encoding
      raise "Unexpected encoding from read: #{data.encoding}"
    end
    @buf += data
  end

  def read_n(n, advance)
    is_first = true
    while @pos + n > @buf.bytesize
      if !is_first
        sleep 2
      end
      self.read
      is_first = false
    end
    if advance
      ret = @buf.byteslice(@pos, n)
      @pos += n
      return ret
    end
    nil
  end

  def read_varint
    x = 0
    for i in 0...5
      y = self.read_n(1, true).bytes.first
      x |= (y & 0x7f) << (7 * i)
      if y & 0x80 == 0
        return x
      end
    end
    raise 'Minecraft sent varint that was too big'
  end

  def read_utf8
    n = self.read_varint
    str = self.read_n(n, true)
    str.force_encoding('utf-8')
  end

  def read_long
    bytes = self.read_n(8, true)
    bytes.unpack('q>').first
  end

  def read_packet
    n = self.read_varint
    self.read_n(n, false)
    self.read_varint
  end

  def read_ping
    id = self.read_packet
    if id != 1
      raise "Minecraft did not reply to ping with pong (got #{id})"
    end
    response = self.read_long
    if response != @token
      raise "Minecraft replied to ping #{@token} with pong #{response}"
    end
  end

  def read_status
    id = self.read_packet
    if id != 0
      raise "Unexpected reply from Minecraft for status (got #{id})"
    end
    status = self.read_utf8
    JSON.parse(status)
  end

  def connect
    address = Socket.pack_sockaddr_in(@port, @ip_address)
    @con.write_timeout(TIMEOUT) do
      @con.connect_nonblock(address)
    end
  end

  def send(data)
    @con.write_timeout(TIMEOUT) do
      @con.write_nonblock(data)
    end
  end

  def recv(n)
    @con.read_timeout(TIMEOUT) do
      @con.read_nonblock(n)
    end
  end

  # shoutout to radu
  def nike
    socket = Socket.new(:INET, :STREAM)
    begin
      self.reset(socket)
      self.connect
      self.handshake
      self.status
      ret = self.read_status
      self.ping
      self.read_ping
      return ret
    rescue => e
      msg = "Exception pinging Minecraft: #{e}"
      Rails.logger.error(msg)
      return msg.error!(e)
    ensure
      socket.close
    end
    raise 'Should not reach here'
  end

  def players_online
    status = self.nike
    if status.error?
      return status
    end
    online = status.try(:[], 'players').try(:[], 'online')
    if online.nil?
      return "Minecraft status unexpected format: #{status}".error!(status)
    end
    online
  end
end

app/models/minecraft/properties.rb
class Minecraft::Properties
  include ActiveModel::Model

  DEFAULT_PROPERTIES = {
    'allow-flight' => 'false',
    'allow-nether' => 'true',
    'announce-player-achievements' => 'true',
    'difficulty' => '1',
    'enable-command-block' => '',
    'enable-query' => 'true',
    'force-gamemode' => 'false',
    'gamemode' => '0',
    'generate-structures' => 'true',
    'generator-settings' => '',
    'hardcore' => 'false',
    'level-seed' => '',
    'level-type' => 'DEFAULT',
    'max-build-height' => '256',
    'motd' => 'A Minecraft Server',
    'online-mode' => 'true',
    'op-permission-level' => '4',
    'player-idle-timeout' => '0',
    'pvp' => 'true',
    'spawn-animals' => 'true',
    'spawn-monsters' => 'true',
    'spawn-npcs' => true,
    'spawn-protection' => '16',
    'white-list' => 'false',
  }

  attr_accessor :allow_flight,
    :allow_nether,
    :announce_player_achievements,
    :difficulty,
    :enable_command_block,
    :enable_query,
    :force_gamemode,
    :gamemode,
    :generate_structures,
    :generator_settings,
    :hardcore,
    :level_seed,
    :level_type,
    :max_build_height,
    :motd,
    :online_mode,
    :op_permission_level,
    :player_idle_timeout,
    :pvp,
    :spawn_animals,
    :spawn_monsters,
    :spawn_npcs,
    :spawn_protection,
    :white_list

  def initialize(response)
    self.allow_flight = response['allow-flight']
    self.allow_nether = response['allow-nether']
    self.announce_player_achievements = response['announce-player-achievements']
    self.difficulty = response['difficulty']
    self.enable_command_block = response['enable-command-block']
    self.enable_query = response['enable-query']
    self.force_gamemode = response['force-gamemode']
    self.gamemode = response['gamemode']
    self.generate_structures = response['generate-structures']
    self.generator_settings = response['generator-settings']
    self.hardcore = response['hardcore']
    self.level_seed = response['level-seed']
    self.level_type = response['level-type']
    self.max_build_height = response['max-build-height']
    self.motd = response['motd']
    self.online_mode = response['online-mode']
    self.op_permission_level = response['op-permission-level']
    self.player_idle_timeout = response['player-idle-timeout']
    self.pvp = response['pvp']
    self.spawn_animals = response['spawn-animals']
    self.spawn_monsters = response['spawn-monsters']
    self.spawn_npcs = response['spawn-npcs']
    self.spawn_protection = response['spawn-protection']
    self.white_list = response['white-list']
  end
end

app/views/minecrafts/_create.html.erb
<% if current_user.digital_ocean_missing? %>
	Gamocosm is an <%= link_to 'open source project', source_path %> to help players host cloud Minecraft servers, but Gamocosm doesn't host the servers ourselves.
	Create an account on <%= render_digital_ocean_referral_link('%s (%s)', 'Digital Ocean', digital_ocean_index_path, digital_ocean_index_no_ref_path) %>, a server host, and enter your API token in your <%= link_to 'settings', edit_user_registration_path %>.
	<strong>If you are not a server admin, you can ignore this.</strong>
	Read more about it <%= link_to 'here', digital_ocean_setup_path %>.
<% else %>
	<%= simple_form_for @minecraft, url: minecrafts_path do |f| %>
		<%= f.input :name, input_html: { size: 32 }, required: true %>
		<%= f.simple_fields_for :server do |s_f| %>
			<%= s_f.input :do_size_slug, collection: @do_sizes.collect { |x| [x.descriptor, x.slug] }, as: :select, include_blank: false, label: 'Size' %>
			<%= s_f.input :do_region_slug, collection: @do_regions.collect { |x| [x.name, x.slug] }, as: :select, include_blank: false, label: 'Region (higher tier better)' %>
		<% end %>
		<%= f.input :flavour, collection: Gamocosm::MINECRAFT_FLAVOURS.collect { |k, v| [v[:name], k] }, as: :select, include_blank: false, label: 'Minecraft flavour', required: true %>
		<div>
			<%= render partial: 'flavour', collection: Gamocosm::MINECRAFT_FLAVOURS.map { |k, v| [k, v] } %>
		</div>
		<p class="help-block">
			We recommend vanilla or <%= link_to 'MCServer', mcserver_website_path %>, the performant C++ Minecraft server (you can always change this later).
			<%= link_to 'Read more', wiki_minecraft_versions_path %>
		</p>
		<br />
		<%= link_to 'Digital Ocean pricing page', digital_ocean_pricing_no_ref_path %>
		<button class="btn btn-default pull-right" type="submit">
			Next <i class="fa fa-chevron-right"></i>
		</button>
	<% end %>
<% end %>

app/views/minecrafts/_friend.html.erb
<tr>
	<td><%= friend.email %></td>
	<td>
		<%= simple_form_for :minecraft_friend, url: remove_friend_minecraft_path(@minecraft), method: :post do |f| %>
			<%= f.input :email, as: :hidden, input_html: { value: friend.email } %>
			<%= f.button :submit, 'Remove', class: 'btn btn-default pull-right' %>
		<% end %>
	</td>
</tr>

app/views/minecrafts/_ftp_ssh.html.erb
<br />
<%= panel_with_heading 'Server Credentials' do %>
	FTP and SSH instructions are on the <%= link_to 'wiki', wiki_ftp_ssh_path %>.
	<br /><br />
	<dl>
		<dt>Host</dt><dd><%= render_minecraft_ip_address(@minecraft, 'Your server\'s IP address when running') %></dd>
		<dt>Port</dt><dd>default 4022 (can be changed under the "Advanced" tab)</dd>
		<dt>User</dt><dd>mcuser</dd>
		<dt>Password</dt>
		<dd><ul>
			<li>Default: your email and the name of your server separated with a plus, e.g. "steve@example.com+terrafirmacraft" (<strong>you should change this!</strong>)</li>
			<li>Even if you specify SSH key(s) to add to your server, a password must be set for you to use sudo</li>
		</ul></dd>
		<dt>FTP Protocol</dt><dd>SFTP</dd>
		<dt>FTP Logon Type</dt><dd>Normal (saves password) or Ask for password (every time)</dd>
	</dl>
<% end %>

<%= panel_with_heading 'Changing your server password' do %>
	<ol>
		<li>SSH into your server</li>
		<li>Run <code>passwd</code></li>
		<li>Enter your old and new password into the prompt</li>
		<li>Exit (run <code>exit</code>)</li>
	</ol>
<% end %>

<%= panel_with_heading 'SSH Keys' do %>
	<p>
		The next time you start your server, Gamocosm will add these keys to your list of authorized keys (and reset this field)
	</p>
	<%= simple_form_for @minecraft, (@demo.nil? ? { url: minecraft_path(@minecraft), method: :put } : { html: { onsubmit: 'return false;' } }) do |f| %>
		<%= f.simple_fields_for :server do |s_f| %>
			<%= s_f.input :ssh_keys, label: false, hint: 'Comma separated list of Digital Ocean SSH key IDs (spaces will be stripped)' %>
		<% end %>
		<%= f.button :submit, 'Save', class: 'btn btn-default' %>
	<% end %>
	<hr />
	<h4>SSH keys on Digital Ocean</h4>
	<% if @demo.nil? %>
		<table id="digital_ocean_ssh_keys" class="table table-striped table-no_fixed" data-url="<%= show_digital_ocean_ssh_keys_path %>">
			<tr><td><i>Fetching data ...</i></td></tr>
		</table>
	<% else %>
		<table class="table table-striped table-no_fixed">
			<tr>
				<th>Name</th>
				<th class="text-right">ID</th>
				<th>&nbsp;</th>
			</tr>
			<tr>
				<td>me</td>
				<td class="text-right">123</td>
				<td><a class="btn btn-default pull-right">Delete</a></td>
			</tr>
			<tr>
				<td>gamocosm</td>
				<td class="text-right">456</td>
				<td><a class="btn btn-default pull-right">Delete</a></td>
			</tr>
		</table>
	<% end %>
	<hr />
	<h4>Add SSH public key to Digital Ocean</h4>
	<%= simple_form_for :digital_ocean_ssh_key, (@demo.nil? ? { url: add_digital_ocean_ssh_key_path, method: :post } : { html: { onsubmit: 'return false;' } }) do |f| %>
		<%= f.input :name %>
		<%= f.input :data, as: :text, label: 'SSH Public Key' %>
		<%= f.button :submit, 'Add', class: 'btn btn-default' %>
	<% end %>
<% end %>

app/views/minecrafts/_invalid.html.erb
<div class="row">
	<div class="alert alert-warning">
		<h3>Error communicating with Digital Ocean</h3>
		We got the following error while retrieving information about your server on Digital Ocean: <%= @minecraft.server.remote.error %>
		<br />
		If you are not the server admin, please contact him/her about it.
	</div>
</div>

app/views/minecrafts/_logs.html.erb
<div class="row">
	<div class="col-sm-12">
		<%= panel_with_heading 'Server Log' do %>
			<% if @minecraft.logs.count == 0 %>
				<em>No messages</em>
			<% else %>
				<% @minecraft.logs.order('created_at DESC').each do |x| %>
					<p><div>
						<%= x.when %>
						<div class="pull-right"><%= x.debuginfo %></div>
						<br />
						<%= x.message %>
					</div></p>
				<% end %>
				<% if @minecraft.owner?(current_user) %>
					<%= link_to 'Clear', clear_logs_minecraft_path(@minecraft), class: 'btn btn-default pull-right' %>
				<% end %>
			<% end %>
		<% end %>
	</div>
</div>

app/views/minecrafts/_profile.html.erb
<div class="row">
	<div class="col-sm-6">
		<%= panel_with_heading 'Domain / IP Address' do %>
			<%= render_minecraft_ip_address(@minecraft) %>
			<br />
			<%= link_to 'Learn more', info_path %>
		<% end %>
	</div>
	<div class="col-sm-6">
		<%=panel_with_heading 'Status' do %>
			<%= render_server_status(@minecraft) %>
		<% end %>
	</div>
</div>
<% if @minecraft.owner?(current_user) && @minecraft.running? %>
	<div class="row">
		<div class="col-sm-12">
			<%= panel_with_heading 'Send Command to Server' do %>
				<%= simple_form_for :command, (@demo.nil? ? { url: command_minecraft_path(@minecraft) } : { html: { onsubmit: 'return false;' } }) do |f| %>
					<%= f.input :data, as: :string %>
					<%= f.button :submit, 'Send', class: 'btn btn-success' %>
				<% end %>
			<% end %>
		</div>
	</div>
<% end %>
<% if @minecraft.owner?(current_user) %>
	<div class="row">
		<div class="col-sm-6">
			<%= panel_with_heading 'Friends' do %>
				<table class="table table-striped">
					<tbody>
						<% if @minecraft.friends.blank? %>
							<tr><td colspan="2"><em>Tell your friends to sign up and add them to your server to let them start and stop it when you're offline.</em></td></tr>
						<% else %>
							<%= render partial: 'friend', collection: @minecraft.friends %>
						<% end %>
					</tbody>
				</table>
				<%= simple_form_for :minecraft_friend, (@demo.nil? ? { url: add_friend_minecraft_path(@minecraft), method: :post } : { html: { onsubmit: 'return false;' } }) do |f| %>
					<%= f.input :email %>
					<%= f.button :submit, 'Add', class: 'btn btn-default' %>
				<% end %>
			<% end %>
		</div>
		<div class="col-sm-6">
			<%= panel_with_heading 'Autoshutdown' do %>
				Autoshutdown is <strong><%= @minecraft.autoshutdown_enabled ? 'enabled' : 'disabled' %></strong>
				<br />
				Last check: <strong><%= @minecraft.autoshutdown_last_check.nil? ? 'n/a' : (time_ago_in_words(@minecraft.autoshutdown_last_check) + ' ago') %></strong>
				<br />
				Last successful check: <strong><%= @minecraft.autoshutdown_last_successful.nil? ? 'n/a' : (time_ago_in_words(@minecraft.autoshutdown_last_successful) + ' ago') %></strong>
				<br />
				<% if @demo.nil? %>
					<% if @minecraft.autoshutdown_enabled %>
						<%= link_to 'Disable', autoshutdown_disable_minecraft_path(@minecraft), class: 'btn btn-success' %>
					<% else %>
						<%= link_to 'Enable', autoshutdown_enable_minecraft_path(@minecraft), class: 'btn btn-success' %>
					<% end %>
				<% else %>
					<a class="btn btn-success">Enable</a>
				<% end %>
				<br />
				<br />
				<i>
					Gamocosm is not responsible if something goes wrong, but it will try to notify you via email.
					It is your responsibility to periodically check on your servers.
					<%= link_to 'Learn more', info_path %>
				</i>
			<% end %>
		</div>
	</div>
<% end %>