config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'pages#landing'

  get 'about', to: 'pages#about', as: :about
  get 'tos', to: 'pages#tos', as: :tos

  get 'badness/:secret', to: 'pages#badness'

  direct :git_head do
    "https://github.com/Gamocosm/Gamocosm/tree/#{Gamocosm::GIT_HEAD}"
  end

  direct :blog do
    'https://gamocosm.com/blog/'
  end

  direct :wiki do |page|
    if page.blank?
      'https://github.com/Gamocosm/Gamocosm/wiki'
    else
      "https://github.com/Gamocosm/Gamocosm/wiki/#{page}"
    end
  end

  direct :issues do
    'https://github.com/Gamocosm/Gamocosm/issues'
  end

  direct :source do
    'https://github.com/Gamocosm/Gamocosm'
  end

  direct :license do
    'https://github.com/Gamocosm/Gamocosm/blob/master/LICENSE'
  end

  direct :cuberite_website do
    'https://cuberite.org'
  end

  direct :gitter_lobby do
    'https://gitter.im/gamocosm/Lobby'
  end

  direct :digital_ocean_control_panel do
    'https://cloud.digitalocean.com'
  end

  direct :digital_ocean_status do
    'https://status.digitalocean.com'
  end

  direct :digital_ocean_api_setup do
    'https://docs.digitalocean.com/reference/api/create-personal-access-token/'
  end

  namespace :digital_ocean do
    resources :droplets, only: [:index, :destroy]

    resources :images, only: [:index, :destroy]

    resources :ssh_keys, only: [:index, :create, :destroy]

    resources :volumes, only: [:index, :destroy]

    resources :snapshots, only: [:index, :destroy]

    delete 'cache', to: '/servers#refresh_digital_ocean_cache', as: :refresh_cache
  end

  get 'servers/new', to: 'servers#new', as: :new_server
  post 'servers/new', to: 'servers#create', as: nil
  resources :servers, only: [:index, :show, :update, :destroy] do
    member do
      get 'confirm_delete'

      post 'start'
      post 'stop'
      post 'reboot'

      post 'pause'
      post 'resume'
      post 'command'
      post 'backup'
      get 'download'

      put 'update_properties'

      post 'add_friend'
      post 'remove_friend'

      post 'autoshutdown_enable'
      post 'autoshutdown_disable'

      delete 'clear_logs'

      scope path: 'api/:key', as: :api, controller: :api do
        get 'status'
        post 'start'
        post 'stop'
        post 'reboot'
        post 'pause'
        post 'resume'
        post 'backup'
        post 'exec'
      end
    end
  end

  resources :volumes, only: [:index, :new, :show, :edit, :create, :update, :destroy] do
    member do
      get 'confirm_delete'
      post 'suspend'
      post 'reload'
    end
  end

  devise_for :users, controllers: { registrations: :registrations }

  if Rails.env.production?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV['SIDEKIQ_USERNAME'])) &
        ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV['SIDEKIQ_PASSWORD']))
    end
  end
  mount Sidekiq::Web => '/sidekiq'

  match '*unused', to: 'pages#not_found', via: :all

end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_action :authenticate_user!

  def index
    @servers = current_user.servers
    @friend_servers = current_user.friend_servers
  end

  def show
    @server = find_server
  end

  def new
    @server = Server.new
    @server.minecraft = Minecraft.new
    @do_regions = Gamocosm.digital_ocean.region_list
    @do_sizes = Gamocosm.digital_ocean.size_list
  end

  def create
    begin
      @server = current_user.servers.create!(server_params)
      redirect_to server_path(@server), flash: { success: 'You made a new server! Start it to play' }
    rescue
      @server = Server.new(server_params)
      # run validations for error messages
      @server.valid?
      flash[:error] = 'Something went wrong. Please try again'

      @do_regions = Gamocosm.digital_ocean.region_list
      @do_sizes = Gamocosm.digital_ocean.size_list
      render :new
    end
  end

  def update
    @server = find_server_only_owner
    # can be ftp ssh tab, schedule tab, or advanced tab
    ssh_keys = server_ssh_keys_params[:ssh_keys]
    if ssh_keys.nil?
      p = server_schedule_params
      @server_tab = :schedule
      schedule_text = nil
      if p[:timezone_delta].nil?
        p = server_advanced_params
        if !p[:minecraft_attributes].nil?
          p[:minecraft_attributes][:id] = @server.minecraft.id
        end
        @server_tab = :advanced
      else
        if !p[:minecraft_attributes].nil?
          p[:minecraft_attributes][:id] = @server.minecraft.id
        end
        schedule_text = p.delete(:schedule_text)
      end
      if @server.update(p)
        if @server_tab != :schedule || @server.parse_and_save_schedule(schedule_text)
          return redirect_to server_path(@server), flash: { success: (@server_tab == :schedule ? 'Server schedule updated' : 'Server advanced configuration updated') }
        end
      end
    else
      @server.ssh_keys = ssh_keys
      if @server.save
        message = 'Server SSH keys updated'
        if !@server.ssh_keys.blank?
          message += '. They will be added the next time you start the server'
        end
        return redirect_to server_path(@server), flash: { success: message }
      end
      @server_tab = :ftp_ssh
    end
    flash[:error] = 'Something went wrong. Please try again'
    render :show
  end

  def destroy
    @server = find_server_only_owner
    if !@server.preserve_snapshot
      error = @server.remote.destroy_saved_snapshot
      if error
        return redirect_to server_path(@server), flash: { error: "Unable to delete saved server snapshot: #{error}" }
      end
    end
    error = @server.remote.destroy
    if error
      return redirect_to server_path(@server), flash: { error: "Unable to delete server: #{error}" }
    end
    @server.delete
    redirect_to servers_path, flash: { success: 'Server is deleting' }
  end

  def confirm_delete
    @server = find_server_only_owner
  end

  def start
    @server = find_server
    error = @server.start
    if error
      flash[:error] = "Unable to start server: #{error}. Please contact the server admin about this"
    else
      flash[:success] = 'Server starting'
    end
    @server.user.invalidate_digital_ocean_cache_droplets
    @server.user.invalidate_digital_ocean_cache_volumes
    @server.user.invalidate_digital_ocean_cache_snapshots
    redirect_to server_path(@server)
  end

  def stop
    @server = find_server
    error = @server.stop
    if error
      flash[:error] = "Unable to stop server: #{error}. Please contact the server admin about this"
    else
      flash[:success] = 'Server stopping'
    end
    redirect_to server_path(@server)
  end

  def reboot
    @server = find_server
    error = @server.reboot
    if error
      flash[:error] = "Unable to reboot server: #{error}. Please contact the server admin about this"
    else
      flash[:success] = 'Server is rebooting'
    end
    redirect_to server_path(@server)
  end

  def resume
    @server = find_server
    error = @server.minecraft.resume
    if error
      flash[:error] = "Unable to start Minecraft: #{error}. Please contact the server admin about this"
    else
      flash[:success] = 'Server resumed'
    end
    redirect_to server_path(@server)
  end

  def pause
    @server = find_server
    error = @server.minecraft.pause
    if error
      flash[:error] = "Unable to stop Minecraft: #{error}. Please contact the server admin about this"
    else
      flash[:success] = 'Server paused'
    end
    redirect_to server_path(@server)
  end

  def backup
    @server = find_server
    error = @server.minecraft.backup
    if error
      flash[:error] = "Unable to backup world: #{error}. Please contact the server admin about this"
    else
      flash[:success] = 'World backed up remotely on server'
    end
    redirect_to server_path(@server)
  end

  def download
    @server = find_server
    error = @server.minecraft.download?
    if error
      return redirect_to server_path(@server), flash: { error: "Unable to download world: #{error}. Please contact the server admin about this" }
    end
    redirect_to @server.minecraft.world_download_url, allow_other_host: true
  end

  def command
    @server = find_server
    command = minecraft_command_params[:data]
    error = @server.minecraft.exec(current_user, command)
    if error
      return redirect_to server_path(@server), flash: { error: "Unable to send command to Minecraft: #{error}. Please contact the server admin about this" }
    end
    redirect_to server_path(@server), flash: { success: 'Command sent' }
  end

  def update_properties
    @server = find_server_only_owner
    if !@server.running?
      return redirect_to server_path(@server), flash: { error: 'Server isn\'t running. Start it to edit Minecraft properties' }
    end
    res = @server.minecraft.node.update_properties(minecraft_properties_params)
    if res.error?
      return redirect_to server_path(@server), flash: { error: "Unable to update Minecraft properties: #{res}. Please contact the server admin about this" }
    end
    redirect_to server_path(@server), flash: { success: 'Minecraft properties updated' }
  end

  def add_friend
    @server = find_server_only_owner
    email = server_friend_params[:email]
    friend = User.find_by_email(email)
    if friend.nil?
      return redirect_to server_path(@server), flash: { error: "User #{email} does not exist" }
    end
    if @server.owner?(friend)
      return redirect_to server_path(@server), notice: 'You are already the owner of the server'
    end
    if @server.friend?(friend)
      return redirect_to server_path(@server), notice: "User #{email} is already on this server"
    end
    @server.friends << friend
    redirect_to server_path(@server), flash: { success: "User #{email} added to the server" }
  end

  def remove_friend
    @server = find_server_only_owner
    email = server_friend_params[:email]
    friend = User.find_by_email(email)
    if friend.nil?
      return redirect_to server_path(@server), flash: { error: "User #{email} does not exist" }
    end
    @server.friends.delete(friend)
    redirect_to server_path(@server), flash: { success: "User #{email} removed from the server" }
  end

  def autoshutdown_enable
    @server = find_server_only_owner
    @server.minecraft.update_columns(autoshutdown_enabled: true)
    if @server.remote.exists?
      AutoshutdownMinecraftWorker.perform_in(AutoshutdownMinecraftWorker::CHECK_INTERVAL, @server.id)
    end
    redirect_to server_path(@server), flash: { success: 'Autoshutdown enabled' }
  end

  def autoshutdown_disable
    @server = find_server_only_owner
    @server.minecraft.update_columns(autoshutdown_enabled: false)
    redirect_to server_path(@server), flash: { success: 'Autoshutdown disabled' }
  end

  def clear_logs
    @server = find_server_only_owner
    @server.logs.delete_all
    redirect_to server_path(@server), flash: { success: 'Server logs cleared' }
  end

  def refresh_digital_ocean_cache
    current_user.invalidate
    redirect_to servers_path, flash: { success: 'Cache refreshed' }
  end

  private
  def find_server
    begin
      server = Server.find(params[:id])
    rescue
      raise ActionController::RoutingError, 'Not found'
    end
    if server.owner?(current_user) || server.friend?(current_user)
      return server
    end
    raise ActionController::RoutingError, 'Not found'
  end

  def find_server_only_owner
    begin
      current_user.servers.find(params[:id])
    rescue
      raise ActionController::RoutingError, 'Not found'
    end
  end

  def server_params
    params.require(:server).permit(
      :name,
      :remote_region_slug,
      :remote_size_slug,
      minecraft_attributes: [:flavour],
    )
  end

  def minecraft_properties_params
    params.require(:minecraft_properties).permit(
      :allow_flight,
      :allow_nether,
      :announce_player_achievements,
      :difficulty,
      :enable_command_block,
      :force_gamemode,
      :gamemode,
      :generate_structures,
      :generator_settings,
      :hardcore,
      :level_seed,
      :level_type,
      :max_build_height,
      :motd,
      :online_mode,
      :op_permission_level,
      :player_idle_timeout,
      :pvp,
      :spawn_animals,
      :spawn_monsters,
      :spawn_npcs,
      :spawn_protection,
      :white_list,
      :whitelist,
      :ops,
    )
  end

  def server_friend_params
    params.require(:server_friend).permit(:email)
  end

  def server_advanced_params
    params.require(:server).permit(
      :ssh_port,
      :setup_stage,
      :pending_operation,
      :remote_snapshot_id,
      :remote_region_slug,
      :remote_size_slug,
      :api_key,
      :preserve_snapshot,
      minecraft_attributes: [:mcsw_password],
    )
  end

  def server_ssh_keys_params
    params.require(:server).permit(:ssh_keys)
  end

  def server_schedule_params
    params.require(:server).permit(
      :timezone_delta,
      :schedule_text,

app/helpers/servers_helper.rb
module ServersHelper
  def server_status_class(server)
    if server.pending_operation
      'text-warning'
    elsif server.remote.error?
      'text-danger'
    elsif server.running?
      'text-success'
    else
      'text-muted'
    end
  end

  def server_minecraft_status_class(server)
    if !server.busy? && server.minecraft.pause?.nil?
      'text-success'
    else
      'text-muted'
    end
  end

  def breadcrumb_back_to_servers
    link_to servers_path, class: 'basic-breadcrumb' do
      "Servers <span class='fa fa-angle-right'></span>".html_safe
    end
  end
end

app/views/servers/_advanced.html.erb
<%= simple_form_for @server, url: server_path(@server), method: :put do |f| %>
	<%= panel_with_heading 'Advanced Configuration' do %>
		View the documentation for these fields on the <%= link_to 'wiki', wiki_url('Server-Advanced-Tab-Documentation') %>.
		<br /><br />
		<%= f.input :ssh_port, label: 'SSH port' %>
		<%= f.input :pending_operation %>
		<%= f.input :setup_stage %>
		<%= f.input :remote_snapshot_id, label: 'Digital Ocean saved snapshot id' %>
		<%= f.input :remote_region_slug, label: 'Digital Ocean region slug' %>
		<%= f.input :remote_size_slug, label: 'Digital Ocean size slug' %>
		<%= f.input :api_key, label: 'API key' %>
		<p class="help-block">
			Example: <code><%= url_for status_api_server_path(@server, @server.api_key) %></code>.
		</p>
		<%= f.input :preserve_snapshot, label: 'Preserve snapshot', as: :select, include_blank: false %>
		<%= f.simple_fields_for :minecraft do |f_m| %>
			<%= f_m.input :mcsw_password, label: 'MCSW key', as: :string %>
		<% end %>
		<%= f.button :submit, 'Update', class: 'btn btn-success' %>
	<% end %>
<% end %>

app/views/servers/_busy.html.erb
<% content_for :head do %>
	<meta http-equiv="refresh" content="8" />
<% end %>
<div>
	<% if @server.pending_operation == 'starting' %>
		Your server is being created.
		<% if !@server.done_setup? %>
			This should take a few minutes (first time only).
		<% else %>
			This should take about a minute.
		<% end %>
	<% elsif @server.pending_operation == 'preparing' %>
		<% if !@server.done_setup? %>
			Your server is being set up.
			This should take a few minutes (first time only).
		<% else %>
			Your server is being started. This should take about a minute.
		<% end %>
		<br />
		Status:
		<% if @server.setup_stage == 0 %>
			Connecting
		<% elsif @server.setup_stage == 1 %>
			Installing and updating software (usually 2-5 minutes)
		<% elsif @server.setup_stage == 2 %>
			Adding SSH keys
		<% elsif @server.setup_stage == 3 %>
			Downloading and installing Minecraft (<%= @server.minecraft.flavour_info.try(:[], :name) %>, estimated <%= pluralize_with_count(@server.minecraft.flavour_info.try(:[], :time), 'minute') %>)
		<% elsif @server.setup_stage == 4 %>
			Finishing up
		<% elsif @server.setup_stage == 5 %>
			Keeping the system up to date
		<% end %>
	<% elsif @server.pending_operation == 'stopping' %>
		Your server is shutting down.
		This should take about 15 seconds.
	<% elsif @server.pending_operation == 'saving' %>
		Your server is being backed up.
		This should take about a minute.
	<% elsif @server.pending_operation == 'rebooting' %>
		Your server is rebooting.
		This should only take a few seconds.
	<% else %>
		Hmmmm.
	<% end %>
	<br />
	This page will automatically refresh itself, but feel free to refresh it yourself.
	<hr />
	<%= render partial: 'advanced' %>
	<%= render partial: 'logs' %>
	<hr />
	<%= link_to 'Delete', confirm_delete_server_path(@server), class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this server forever? (A really long time!)' } %>
</div>
<br />

app/views/servers/_flavour.html.erb
<div class="minecraft_flavour-info well" data-flavour="<%= flavour.first %>">
	<dl>
		<dt>Website</dt>
		<dd><%= link_to flavour.second[:website], flavour.second[:website] %></dd>
		<dt>Developers</dt>
		<dd><%= flavour.second[:developers].join(', ') %></dd>
		<dt>Install (first time only)</dt>
		<dd><%= pluralize(flavour.second[:time], 'minute') %> (+4 minutes base)</dd>
		<% if !flavour.second[:notes].blank? %>
			<dt>Notes</dt>
			<dd><ul>
				<% flavour.second[:notes].each do |n| %>
					<li><%= n %></li>
				<% end %>
			</ul></dd>
		<% end %>
	</dl>
</div>

app/views/servers/_friend.html.erb
<li>
	<%= simple_form_for :server_friend, url: remove_friend_server_path(@server), method: :post do |f| %>
		<%= f.input :email, as: :hidden, input_html: { value: friend.email } %>
		<div class="friend">
			<span class="email"><%= friend.email %></span>
			<span class="actions">
				<%= f.button :submit, 'Remove', class: 'btn btn-default' %>
			</span>
		</div>
	<% end %>
</li>

app/views/servers/_ftp_ssh.html.erb
<%= panel_with_heading 'Server Credentials' do %>
	<p>SSH and FTP instructions are on the <%= link_to 'wiki', wiki_url('FTP-and-SSH') %>.</p>
	<table class="ftp-details table">
		<tr><th scope="row">Host</th><td><%= render_server_ip_address(@server, 'Your server\'s IP address when running') %></td></tr>
		<tr><th scope="row">Port</th><td><%= @server.ssh_port %></td></tr>
		<tr><th scope="row">User</th><td>mcuser</td></tr>
		<tr><th scope="row">Password</th>
		<td><p>Defaults to your email and the name of your server separated with a plus, e.g. "steve@example.com+terrafirmacraft" (<strong>you should change this!</strong>)</p>
			<p>Even if you specify SSH key(s) to add to your server, a password must be set for you to use sudo</p>
		</td></tr>
		<tr><th scope="row">FTP Protocol</th><td>SFTP</td></tr>
		<tr><th scope="row">FTP Logon Type</th><td>Normal (saves password) or Ask for password (every time)</td></tr>
	</table>
<% end %>

<%= panel_with_heading 'Changing your server password' do %>
	<ol>
		<li>SSH into your server, or use the <%= link_to 'web console', wiki_url('Web-Console') %> (and go to the terminal).</li>
		<li>Run <code>passwd</code> and follow the prompts.</li>
	</ol>
<% end %>

<%= panel_with_heading 'SSH Keys' do %>
	<p>
		The next time you start your server, Gamocosm will add these keys to your list of authorized keys (and reset this field)
	</p>
	<%= form_for @server, url: server_path(@server), method: :put do |f| %>
		<%= f.label :ssh_keys, class: "sr-only" %>
		<div class="input-group">
			<%= f.text_field :ssh_keys, class: "form-control" %>
			<span class="input-group-btn">
				<%= f.submit 'Save', class: 'btn btn-default' %>
			</span>
		</div>
		<p class="help-block">Comma separated list of Digital Ocean SSH key IDs (spaces will be stripped)</p>
	<% end %>
	<hr />
	<h4>SSH keys on Digital Ocean</h4>
	<table id="digital_ocean_ssh_keys" class="table table-striped table-no_fixed" data-url="<%= digital_ocean_ssh_keys_path %>">
		<tr><td><i>Fetching data ...</i></td></tr>
	</table>
	<hr />
	<h4>Add SSH public key to Digital Ocean</h4>
	<%= simple_form_for :digital_ocean_ssh_key, url: digital_ocean_ssh_keys_path do |f| %>
		<%= f.input :name %>
		<%= f.input :data, as: :text, label: 'SSH Public Key' %>
		<%= f.button :submit, 'Add', class: 'btn btn-default' %>
	<% end %>
<% end %>

app/views/servers/_logs.html.erb
<div class="row">
	<div class="col-sm-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="panel-title">
					Server Log (<%= @server.logs.size %>)
				</h4>
			</div>
			<div id="server_log_panel" class="panel-body">
				<% if @server.logs.count == 0 %>
					<em>No messages</em>
				<% else %>
					<table class="table table-striped">
						<tbody>
							<% @server.logs.order('created_at DESC').each do |x| %>
								<tr>
									<td>
										<div>
											<%= x.when %>
											<div class="pull-right"><%= x.debuginfo %></div>
										</div>
										<p>
											<%= x.message %>
										</p>
									</td>
								</tr>
							<% end %>
						</tbody>
					</table>
					<% if @server.owner?(current_user) %>
						<%= link_to 'Clear', clear_logs_server_path(@server), method: :delete, class: 'btn btn-default pull-right' %>
					<% end %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/servers/_tips.html.erb
<div class="row">
	<div class="col-sm-12">
		<%= panel_with_heading 'Information' do %>
			<ul>
				<li>Always back up your server and keep your own copies!</li>
				<li>Stop the physical server when no-one is playing.
				Digital Ocean charges you when the server is running.
				</li>
				<li>Stop Minecraft before backing up or downloading your world, or editing files (configuration, mods, plugins, etc.).</li>
				<li>For more information read the <%= link_to 'About page', about_path %> or the <%= link_to 'wiki', wiki_url %>.</li>
				<li>Read more about using different version of Minecraft or specifying JVM arguments on the <%= link_to 'wiki', wiki_url('Installing-Different-Versions-of-Minecraft') %>.</li>
				<li>Server taking a long time to start/stop? Read about using volumes on the <%= link_to 'wiki', wiki_url('Using-Digital-Ocean-Volumes') %>.</li>
				<li>For problems, check the <%= link_to 'Troubleshooting page', wiki_url('Troubleshooting') %> on the wiki, or submit an issue on <%= link_to 'GitHub', issues_url %>.</li>
			</ul>
		<% end %>
	</div>
</div>

app/views/servers/confirm_delete.html.erb
<% title "#{@server.name} - Gamocosm" %>
<% if @server.remote.error? %>
	<%= render partial: 'invalid' %>
<% end %>
<div class="row">
	<div class="col-sm-12">
		<div class="page-header">
			<%= breadcrumb_back_to_servers %>
			<h1>
				<%= @server.name %>
				<small><%= @server.remote_region_slug %>-<%= @server.remote_size_slug %></small>
			</h1>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-sm-12">
		<p>
			Are you sure you want to delete server <strong><%= @server.name %></strong> forever? (A really long time!)
		</p>
		<% if @server.remote.exists? || !@server.remote_snapshot_id.nil? %>
			<p>
				If you delete this server now, Gamocosm will also delete the following resources on Digital Ocean:
				<ul>
					<% if @server.remote.exists? || (!@server.remote_snapshot_id.nil? && !@server.preserve_snapshot) %>
						<% if @server.remote.exists? %>
							<li>Droplet #<%= @server.remote_id %></li>
						<% end %>
						<% if !@server.remote_snapshot_id.nil? && !@server.preserve_snapshot %>
							<li>Snapshot #<%= @server.remote_snapshot_id %></li>
						<% end %>
					<% else %>
						<li>No resources to be deleted.</li>
					<% end %>
				</ul>
				<% if !@server.remote_snapshot_id.nil? && @server.preserve_snapshot %>
					<p>
						Your snapshot #<%= @server.remote_snapshot_id %> will be preserved as you have <strong>preserve snapshot</strong> enabled.
					</p>
				<% end %>
				<strong>Please download your Minecraft world (and any other data)!</strong>
			</p>
		<% end %>
		<% if !@server.volume.nil? %>
			<p>
			The volume <strong><%= link_to @server.volume.name, volume_path(@server.volume) %></strong> is attached to this server.
				<% if @server.volume.remote_exists? %>
					Note that:
					<ul>
						<li>
							Gamocosm will not delete the volume automatically, and you will be billed for it on Digital Ocean.
							You must delete it separately on the <%= link_to 'Volumes page', volumes_path %>.
						</li>
						<li>
							<strong>Download your world from the volume!</strong>
							While deleting this server will not delete the volume,
							it will be inconvenient to retrieve your world afterwards.
						</li>
					</ul>
				<% end %>
			</p>
		<% end %>
		<hr />
		<%= link_to server_path(@server), class: "btn btn-success" do %>
			Go back
		<% end %>
		<span class="info-box pull-right">
			<%= link_to 'Delete', server_path(@server), method: :delete, class: "btn btn-danger", data: { confirm: 'Yes. I am Eater of Worlds (an EthosLab reference).' } %>
		</span>
	</div>
</div>

app/views/servers/delete.html.erb
<% title "#{@server.name} - Gamocosm" %>
<% if @server.remote.error? %>
	<%= render partial: 'invalid' %>
<% end %>
<div class="row">
	<div class="col-sm-12">
		<div class="page-header">
			<%= breadcrumb_back_to_servers %>
			<h1>
				<%= @server.name %>
				<small><%= @server.remote_region_slug %>-<%= @server.remote_size_slug %></small>
			</h1>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-sm-12">
		<p>
			Are you sure you want to delete server <strong><%= @server.name %></strong> forever? (A really long time!)
		</p>
		<% if @server.remote.exists? || !@server.remote_snapshot_id.nil? %>
			<p>
				If you delete this server now, Gamocosm will also delete the following resources on Digital Ocean:
				<ul>
					<% if @server.remote.exists? || (!@server.remote_snapshot_id.nil? && !@server.preserve_snapshot) %>
						<% if @server.remote.exists? %>
							<li>Droplet #<%= @server.remote_id %></li>
						<% end %>
						<% if !@server.remote_snapshot_id.nil? && !@server.preserve_snapshot %>
							<li>Snapshot #<%= @server.remote_snapshot_id %></li>
						<% end %>
					<% else %>
						<li>No resources to be deleted.</li>
					<% end %>
				</ul>
				<% if !@server.remote_snapshot_id.nil? && @server.preserve_snapshot %>
					<p>
						Your snapshot #<%= @server.remote_snapshot_id %> will be preserved as you have <strong>preserve snapshot</strong> enabled.
					</p>
				<% end %>
				<strong>Please download your Minecraft world (and any other data)!</strong>
			</p>
		<% end %>
		<% if !@server.volume.nil? %>
			<p>
			The volume <strong><%= link_to @server.volume.name, volume_path(@server.volume) %></strong> is attached to this server.
				<% if @server.volume.remote_exists?  %>
					Note that:
					<ul>
						<li>
							Gamocosm will not delete the volume automatically, and you will be billed for it on Digital Ocean.
							You must delete it separately on the <%= link_to 'Volumes page', volumes_path %>.
						</li>
						<li>
							<strong>Download your world from the volume!</strong>
							While deleting this server will not delete the volume,
							it will be inconvenient to retrieve your world afterwards.
						</li>
					</ul>
				<% end %>
			</p>
		<% end %>
		<hr />
		<%= link_to server_path(@server), class: "btn btn-success" do %>
			Go back
		<% end %>
		<span class="info-box pull-right">
			<%= link_to 'Delete', server_path(@server), method: :delete, class: "btn btn-danger", data: { confirm: 'Yes. I am Eater of Worlds (an EthosLab reference).' } %>
		</span>
	</div>
</div>