config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'pages#landing'

  get 'about', to: 'pages#about', as: :about
  get 'tos', to: 'pages#tos', as: :tos

  get 'badness/:secret', to: 'pages#badness'

  direct :git_head do
    "https://github.com/Gamocosm/Gamocosm/tree/#{Gamocosm::GIT_HEAD}"
  end

  direct :blog do
    'https://gamocosm.com/blog/'
  end

  direct :wiki do |page|
    if page.blank?
      'https://github.com/Gamocosm/Gamocosm/wiki'
    else
      "https://github.com/Gamocosm/Gamocosm/wiki/#{page}"
    end
  end

  direct :issues do
    'https://github.com/Gamocosm/Gamocosm/issues'
  end

  direct :source do
    'https://github.com/Gamocosm/Gamocosm'
  end

  direct :license do
    'https://github.com/Gamocosm/Gamocosm/blob/master/LICENSE'
  end

  direct :cuberite_website do
    'https://cuberite.org'
  end

  direct :gitter_lobby do
    'https://gitter.im/gamocosm/Lobby'
  end

  direct :digital_ocean_control_panel do
    'https://cloud.digitalocean.com'
  end

  direct :digital_ocean_status do
    'https://status.digitalocean.com'
  end

  direct :digital_ocean_api_setup do
    'https://docs.digitalocean.com/reference/api/create-personal-access-token/'
  end

  namespace :digital_ocean do
    resources :droplets, only: [:index, :destroy]

    resources :images, only: [:index, :destroy]

    resources :ssh_keys, only: [:index, :create, :destroy]

    resources :volumes, only: [:index, :destroy]

    resources :snapshots, only: [:index, :destroy]

    delete 'cache', to: '/servers#refresh_digital_ocean_cache', as: :refresh_cache
  end

  get 'servers/new', to: 'servers#new', as: :new_server
  post 'servers/new', to: 'servers#create', as: nil
  resources :servers, only: [:index, :show, :update, :destroy] do
    member do
      get 'confirm_delete'

      post 'start'
      post 'stop'
      post 'reboot'

      post 'pause'
      post 'resume'
      post 'command'
      post 'backup'
      get 'download'

      put 'update_properties'

      post 'add_friend'
      post 'remove_friend'

      post 'autoshutdown_enable'
      post 'autoshutdown_disable'

      delete 'clear_logs'

      scope path: 'api/:key', as: :api, controller: :api do
        get 'status'
        post 'start'
        post 'stop'
        post 'reboot'
        post 'pause'
        post 'resume'
        post 'backup'
        post 'exec'
      end
    end
  end

  resources :volumes, only: [:index, :new, :show, :edit, :create, :update, :destroy] do
    member do
      get 'confirm_delete'
      post 'suspend'
      post 'reload'
    end
  end

  devise_for :users, controllers: { registrations: :registrations }

  if Rails.env.production?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV['SIDEKIQ_USERNAME'])) &
        ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV['SIDEKIQ_PASSWORD']))
    end
  end
  mount Sidekiq::Web => '/sidekiq'

  match '*unused', to: 'pages#not_found', via: :all

end

app/models/volume.rb
# == Schema Information
#
# Table name: volumes
#
#  id                 :uuid             not null, primary key
#  user_id            :integer          not null
#  server_id          :uuid
#  name               :string           not null
#  status             :string           not null
#  remote_id          :string
#  remote_size_gb     :integer          not null
#  remote_region_slug :string           not null
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#
class Volume < ApplicationRecord
  belongs_to :user
  belongs_to :server, optional: :true

  validates :name, length: { in: 3...32 }
  validates :name, format: { with: /\A[a-z][a-z0-9-]*[a-z0-9]\z/, message: 'Name must start with a letter, and end with a letter or number. May include letters, numbers, and dashes in between. Must be lower case' }
  validates :status, inclusion: { in: %w(volume snapshot), message: '%{value} is not a valid status' }
  validates :remote_size_gb, numericality: { only_integer: true, greater_than: 0 }, allow_nil: false
  validates :remote_region_slug, presence: true

  after_initialize :after_initialize_callback
  before_validation :before_validation_callback

  def after_initialize_callback
    self.status ||= 'volume'
  end

  def before_validation_callback
    self.server_id = self.server_id.clean
    self.remote_id = self.remote_id.clean
    if self.remote_id.nil?
      self.status = 'volume'
    end
  end

  def volume?
    self.status == 'volume'
  end

  def snapshot?
    self.status == 'snapshot'
  end

  def remote_exists?
    !self.remote_id.nil?
  end

  def remote
    if !self.volume?
      raise 'Badness'
    end
    if self.remote_id.nil?
      return nil
    end
    if @remote.nil?
      @remote = self.user.digital_ocean.volume_show(self.remote_id)
    end
    @remote
  end

  def remote_snapshot
    if !self.snapshot?
      raise 'Badness'
    end
    if self.remote_id.nil?
      return nil
    end
    if @remote_snapshot.nil?
      @remote_snapshot = self.user.digital_ocean.snapshot_show(self.remote_id)
    end
    @remote_snapshot
  end

  def vivify!
    if self.remote_id.nil?
      res = self.user.digital_ocean.volume_create(self.do_name, self.remote_size_gb, self.remote_region_slug, nil)
      if res.error?
        return res
      end
      self.update_columns(status: 'volume', remote_id: res.id)
      return nil
    end
    if self.volume?
      return nil
    end
    if self.snapshot?
      res = self.user.digital_ocean.volume_create(self.do_name, self.remote_size_gb, self.remote_region_slug, self.remote_id)
      if res.error?
        return res
      end
      self.update_columns(status: 'volume', remote_id: res.id)
      return nil
    end
    raise 'Badness'
  end

  def suspend?
    if self.remote_id.nil?
      return 'Volume has not been created yet.'
    end
    if self.snapshot?
      return 'Volume is already a snapshot.'
    end
    nil
  end

  def reload?
    if self.remote_id.nil?
      return 'Volume has not been created yet.'
    end
    if self.volume?
      return 'Volume is already active.'
    end
    nil
  end

  def suspend!
    error = self.suspend?
    if !error.nil?
      return error.error! nil
    end
    volume_id = self.remote_id
    res = self.user.digital_ocean.volume_snapshot(volume_id, self.do_name)
    if res.error?
      return res
    end
    self.update_columns(status: 'snapshot', remote_id: res.id)
    res = self.user.digital_ocean.volume_delete(volume_id)
    if res.error?
      return res
    end
    nil
  end

  def reload!
    error = self.reload?
    if !error.nil?
      return error.error! nil
    end
    snapshot_id = self.remote_id
    res = self.user.digital_ocean.volume_create(self.do_name, self.remote_size_gb, self.remote_region_slug, snapshot_id)
    if res.error?
      return res
    end
    self.update_columns(status: 'volume', remote_id: res.id)
    res = self.user.digital_ocean.snapshot_delete(snapshot_id)
    if res.error?
      return res
    end
    nil
  end

  def remote_delete
    if self.remote_id.nil?
      return nil
    end
    if self.volume?
      res = self.user.digital_ocean.volume_delete(self.remote_id)
      if res.error?
        return res
      end
      self.update_columns(status: 'volume', remote_id: nil)
      return nil
    end
    if self.snapshot?
      res = self.user.digital_ocean.snapshot_delete(self.remote_id)
      if res.error?
        return res
      end
      self.update_columns(status: 'volume', remote_id: nil)
      return nil
    end
    raise 'Badness'
  end

  def do_name
    'gamocosm-' + self.name
  end

  def mount_path
    "/mnt/#{self.do_name.gsub('-', '_')}"
  end

  def device_path
    "/dev/disk/by-id/scsi-0DO_Volume_#{self.do_name}"
  end
end

app/controllers/digital_ocean/volumes_controller.rb
class DigitalOcean::VolumesController < ApplicationController
  before_action :authenticate_user!
  layout false

  def index
    @do_volumes = current_user.digital_ocean_volumes
  end

  def destroy
    error = current_user.digital_ocean.volume_delete(params[:id])
    current_user.invalidate_digital_ocean_cache_volumes
    if error
      return redirect_to volumes_path, flash: { error: }
    end
    redirect_to volumes_path, flash: { notice: 'Deleted volume on Digital Ocean' }
  end
end

app/controllers/volumes_controller.rb
class VolumesController < ApplicationController
  before_action :set_volume, only: [:show, :edit, :update, :destroy, :delete, :suspend, :reload]
  before_action :authenticate_user!

  def index
    @volumes = current_user.volumes
  end

  def show; end

  def new
    @volume = Volume.new
    @do_regions = Gamocosm.digital_ocean.region_list
  end

  def create
    begin
      @volume = current_user.volumes.create(volume_params)
    rescue ActiveRecord::RecordNotUnique
      @volume = Volume.new(volume_params)
      @do_regions = Gamocosm.digital_ocean.region_list
      flash[:error] = 'The server you selected already has a volume.'
      return render :new
    end

    if @volume.save
      redirect_to @volume, notice: 'Volume was successfully created.'
    else
      @do_regions = Gamocosm.digital_ocean.region_list
      render :new
    end
  end

  def edit
    @do_regions = Gamocosm.digital_ocean.region_list
  end

  def update
    begin
      if @volume.update(volume_params)
        redirect_to @volume, notice: 'Volume was successfully updated.'
      else
        @do_regions = Gamocosm.digital_ocean.region_list
        render :edit
      end
    rescue ActiveRecord::RecordNotUnique
      @do_regions = Gamocosm.digital_ocean.region_list
      flash[:error] = 'The server you selected already has a volume.'
      render :edit
    end
  end

  def destroy
    if !@volume.server.nil?
      return redirect_to volume_path(@volume), flash: { error: "This volume is attached to server #{@volume.server.name}" }
    end
    error = @volume.remote_delete
    @volume.user.invalidate_digital_ocean_cache_volumes
    @volume.user.invalidate_digital_ocean_cache_snapshots
    if error?
      return redirect_to volume_path(@volume), flash: { error: "Error deleting volume on Digital Ocean: #{error}" }
    end
    @volume.destroy
    redirect_to volumes_url, notice: 'Volume was successfully destroyed.'
  end

  def confirm_delete
    render :confirm_delete
  end

  def suspend
    error = @volume.suspend!
    f = { success: 'Volume has been suspended' }
    if error.error?
      f = { error: error.msg }
    end
    @volume.user.invalidate_digital_ocean_cache_volumes
    @volume.user.invalidate_digital_ocean_cache_snapshots
    redirect_to volume_path(@volume), flash: f
  end

  def reload
    error = @volume.reload!
    f = { success: 'Volume has been reloaded' }
    if error.error?
      f = { error: error.msg }
    end
    @volume.user.invalidate_digital_ocean_cache_volumes
    @volume.user.invalidate_digital_ocean_cache_snapshots
    redirect_to volume_path(@volume), flash: f
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_volume
    @volume = Volume.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def volume_params
    params.require(:volume).permit(:name, :status, :remote_id, :remote_size_gb, :remote_region_slug, :server_id)
  end
end

app/helpers/volumes_helper.rb
module VolumesHelper
  def breadcrumb_back_to_volumes
    link_to volumes_path, class: 'basic-breadcrumb' do
      'Volumes <span class="fa fa-angle-right"></span>'.html_safe
    end
  end
end

app/views/volumes/_form.html.erb
<%= simple_form_for(@volume) do |f| %>
	<%= f.error_notification %>

	<div class="form-inputs">
		<%= f.input :name, label: 'Name', hint: 'Lowercase, start with a number, end with a number or letter, numbers, letters, or dashes in between' %>
		<%= f.input :status, label: 'Status', hint: 'Either "volume" or "snapshot"' %>
		<%= f.input :remote_id, label: 'Remote ID', hint: 'Leave blank for a new volume' %>
		<%= f.input :remote_size_gb, label: 'Size (GB)' %>
		<%= f.input :remote_region_slug, collection: @do_regions.collect { |x| [x.name, x.slug] }, as: :select, include_blank: true, label: 'Region', hint: 'Should be the same as your server\'s region' %>
		<%= f.input :server_id, collection: current_user.servers.collect { |x| [ x.name, x.id ] }, as: :select, include_blank: true, label: 'Server', hint: 'Leave blank for no server. Detaching a volume from a server is not recommended.' %>
	</div>

	<div class="form-actions">
		<%= f.button :submit, class: 'btn btn-success' %>
	</div>
<% end %>

app/views/volumes/confirm_delete.html.erb
<% title "Delete Volume #{@volume.name} - Gamocosm" %>
<div class="row">
	<div class="col-sm-12">
		<div class="page-header">
			<%= breadcrumb_back_to_volumes %>
			<h1>
				Volume <%= @volume.name %>
				<small><%= @volume.remote_region_slug %>/<%= @volume.remote_size_gb %> GB</small>
			</h1>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-sm-12">
		<p>
			Are you sure you want to delete volume <strong><%= @volume.name %></strong> forever? (A really long time!)
		</p>
		<% if !@volume.remote_id.nil? %>
			<p>
				If you delete this volume now, Gamocosm will also delete the following resource on Digital Ocean:
				<ul>
					<% if @volume.volume? %>
						<li>Volume <%= @volume.remote_id %></li>
					<% elsif @volume.snapshot? %>
						<li>Snapshot <%= @volume.remote_id %></li>
					<% else %>
						<li><em>Something bad happened</em></li>
					<% end %>
				</ul>
				<strong>Please download your Minecraft world (and any other data)!</strong>
			</p>
		<% end %>
		<% if !@volume.server.nil? %>
			<p>
				This volume is attached to the server <strong><%= link_to @volume.server.name, server_path(@volume.server) %></strong>.
				You will have to manually detach this volume from the server (on the <%= link_to 'Edit page', edit_volume_path(@volume) %>) before deleting this volume.
				Note that:
				<ul>
					<li>Deleting this volume will not automatically delete the server.</li>
					<li>You will still be billed for the server on Digital Ocean.</li>
					<li>You must delete the server separately on the <%= link_to 'Servers page', servers_path %>.</li>
				</ul>
			</p>
		<% end %>
		<hr />
		<%= link_to volume_path(@volume), class: "btn btn-success" do %>
			Go back
		<% end %>
		<span class="info-box pull-right">
			<%= link_to 'Delete', volume_path(@volume), method: :delete, class: "btn btn-danger", data: { confirm: 'Yes. I am Eater of Worlds (an EthosLab reference).' } %>
		</span>
	</div>
</div>

app/views/volumes/delete.html.erb
<% title "Delete Volume #{@volume.name} - Gamocosm" %>
<div class="row">
	<div class="col-sm-12">
		<div class="page-header">
			<%= breadcrumb_back_to_volumes %>
			<h1>
				Volume <%= @volume.name %>
				<small><%= @volume.remote_region_slug %>/<%= @volume.remote_size_gb %> GB</small>
			</h1>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-sm-12">
		<p>
			Are you sure you want to delete volume <strong><%= @volume.name %></strong> forever? (A really long time!)
		</p>
		<% if !@volume.remote_id.nil? %>
			<p>
				If you delete this volume now, Gamocosm will also delete the following resource on Digital Ocean:
				<ul>
					<% if @volume.volume? %>
						<li>Volume <%= @volume.remote_id %></li>
					<% elsif @volume.snapshot? %>
						<li>Snapshot <%= @volume.remote_id %></li>
					<% else %>
						<li><em>Something bad happened</em></li>
					<% end %>
				</ul>
				<strong>Please download your Minecraft world (and any other data)!</strong>
			</p>
		<% end %>
		<% if !@volume.server.nil? %>
			<p>
				This volume is attached to the server <strong><%= link_to @volume.server.name, server_path(@volume.server) %></strong>.
				You will have to manually detach this volume from the server (on the <%= link_to 'Edit page', edit_volume_path(@volume) %>) before deleting this volume.
				Note that:
				<ul>
					<li>Deleting this volume will not automatically delete the server.</li>
					<li>You will still be billed for the server on Digital Ocean.</li>
					<li>You must delete the server separately on the <%= link_to 'Servers page', servers_path %>.</li>
				</ul>
			</p>
		<% end %>
		<hr />
		<%= link_to volume_path(@volume), class: "btn btn-success" do %>
			Go back
		<% end %>
		<span class="info-box pull-right">
			<%= link_to 'Delete', volume_path(@volume), method: :delete, class: "btn btn-danger", data: { confirm: 'Yes. I am Eater of Worlds (an EthosLab reference).' } %>
		</span>
	</div>
</div>

app/views/volumes/edit.html.erb
<% title "Edit Volume #{@volume.name} - Gamocosm" %>
<div class="row">
	<div class="col-sm-12">
		<div class="page-header">
			<%= breadcrumb_back_to_volumes %>
			<h1>
				Volume <%= @volume.name %>
				<small><%= @volume.remote_region_slug %>/<%= @volume.remote_size_gb %> GB</small>
			</h1>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-sm-8 col-sm-offset-2">
		<%= render 'form', volume: @volume %>
		<hr />
		<%= link_to 'Go back', volume_path(@volume), class: "btn btn-default" %>
	</div>
</div>
<br />
<br />

app/views/volumes/index.html.erb
<% title 'My Volumes - Gamocosm' %>
<div class="row">
	<div class="col-sm-12">
		<div class="page-header">
			<h1>
				Volumes <small>for <%= current_user.email %></small>
				<div class="pull-right">
					<%= link_to new_volume_path, class: 'btn btn-lg btn-primary' do %>
						<span class="fa fa-plus"></span> Create volume
					<% end %>
					<%= link_to 'Open a support ticket', issues_url, class: 'btn btn-lg btn-default' %>
				</div>
			</h1>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-sm-12">
		<table class="table table-striped">
			<thead>
				<tr>
					<td colspan="2">Name</td>
					<td colspan="2">Server</td>
					<td>Status</td>
					<td colspan="3">Remote ID</td>
				</tr>
			</thead>
			<tbody>
			<% if @volumes.blank? %>
				<tr>
					<td colspan="8" class="text-center">
						<em>You have no volumes</em>
					</td>
				</tr>
			<% else %>
				<% @volumes.each do |v| %>
					<tr>
						<td colspan="2"><%= link_to v.name, volume_path(v) %></td>
						<td colspan="2"><%= v.server.nil? ? 'n/a' : v.server.name %></td>
						<td><%= v.status %></li>
						<td colspan="3"><%= v.remote_id.nil? ? 'n/a' : v.remote_id %></td>
					</tr>
				<% end %>
			<% end %>
			</tbody>
		</table>
	</div>
</div>

<div class="row">
	<div class="col-sm-12">
		<%= panel_with_heading 'Digital Ocean' do %>
			<div class="row">
				<div class="col-sm-8 col-sm-offset-2">
					This information is provided for you to help you monitor your Digital Ocean account.
					You can always log into <%= link_to 'Digital Ocean\'s control panel', digital_ocean_control_panel_url %> for more control.
					<br />
					<div class="text-center">
						<%= link_to 'Refresh cache', digital_ocean_refresh_cache_path, method: :delete %>
						&bull; <%= link_to 'Digital Ocean status', digital_ocean_status_url %>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-6">
					<h4>Volumes</h4>
					<table id="digital_ocean_volumes" class="table table-striped table-no_fixed" data-url="<%= digital_ocean_volumes_path %>">
						<tr><td><i>Fetching data...</i></td></tr>
					</table>
				</div>
				<div class="col-sm-6">
					<h4>Volume Snapshots</h4>
					<table id="digital_ocean_snapshots" class="table table-striped table-no_fixed" data-url="<%= digital_ocean_snapshots_path %>">
						<tr><td><i>Fetching data...</i></td></tr>
					</table>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/volumes/new.html.erb
<% title 'New Volume - Gamocosm' %>
<div class="row">
	<div class="col-sm-12">
		<div class="page-header">
			<%= breadcrumb_back_to_volumes %>
			<h1>New Volume</h1>
		</div>
	</div>
	<div class="col-sm-8 col-sm-offset-2">
		<%= render 'form', volume: @volume %>
	</div>
</div>
<br />
<br />

app/views/volumes/show.html.erb
<% title "Volume #{@volume.name} - Gamocosm" %>
<div class="row">
	<div class="col-sm-12">
		<div class="page-header">
			<%= breadcrumb_back_to_volumes %>
			<h1>
				Volume <%= @volume.name %>
				<small><%= @volume.remote_region_slug %>/<%= @volume.remote_size_gb %> GB</small>
			</h1>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-sm-8 col-sm-offset-2">
		<h4>Local Information</h4>
		<table class="table table-striped">
			<tbody>
				<tr>
					<td>Server</td>
					<td colspan="3"><%= @volume.server.nil? ? 'n/a' : @volume.server.name %></td>
				</tr>
				<tr>
					<td>Status</td>
					<td colspan="3"><%= @volume.status %></td>
				</tr>
				<tr>
					<td>Remote ID</td>
					<td colspan="3"><%= @volume.remote_id.nil? ? 'n/a' : @volume.remote_id %></td>
				</tr>
				<tr>
					<td>Size (GB)</td>
					<td colspan="3"><%= @volume.remote_size_gb %></td>
				</tr>
				<tr>
					<td>Region</td>
					<td colspan="3"><%= @volume.remote_region_slug %></td>
				</tr>
			</tbody>
		</table>
		<% if !@volume.remote_id.nil? %>
			<% if @volume.volume? %>
				<h4>Remote Volume</h4>
				<% if @volume.remote.error? %>
					<%= @volume.remote %>
				<% else %>
					<p class="help-block">
						The local information above should match this.
					</p>
					<table class="table table-striped">
						<tbody>
							<tr>
								<td>Name</td>
								<td colspan="3"><%= @volume.remote.name %></td>
							</tr>
							<tr>
								<td>Size</td>
								<td colspan="3"><%= @volume.remote.size %></td>
							</tr>
							<tr>
								<td>Region</td>
								<td colspan="3"><%= @volume.remote.region %></td>
							</tr>
						</tbody>
					</table>
				<% end %>
			<% elsif @volume.snapshot? %>
				<h4>Remote Volume Snapshot</h4>
				<% if @volume.remote_snapshot.error? %>
					<%= @volume.remote_snapshot %>
				<% else %>
					<p class="help-block">
						The local information above should match this.
					</p>
					<table class="table table-striped">
						<tbody>
							<tr>
								<td>Name</td>
								<td colspan="3"><%= @volume.remote_snapshot.name %></td>
							</tr>
							<tr>
								<td>Minimum Size</td>
								<td colspan="3"><%= @volume.remote_snapshot.min_disk_size %></td>
							</tr>
							<tr>
								<td>Regions Available</td>
								<td colspan="3"><%= @volume.remote_snapshot.regions.join(', ') %></td>
							</tr>
						</tbody>
					</table>
				<% end %>
			<% else %>
				<p>
					<strong><em>Something bad happened</em></strong>
				</p>
			<% end %>
		<% end %>
		<hr />
		<%= link_to 'Edit', edit_volume_path(@volume), class: "btn btn-success" %>
		<span class="info-box btn-group">
			<% if @volume.suspend?.nil? %>
				<%= link_to suspend_volume_path(@volume), class: 'btn btn-info' do %>
					<span data-toggle="tooltip" data-container="body" title="Suspend this volume for cheaper billing on Digital Ocean">Suspend</span>
				<% end %>
			<% else %>
				<span class="btn btn-info disabled" data-toggle="tooltip" data-container="body" title="<%= @volume.suspend? %>">Suspend</span>
			<% end %>
			<% if @volume.reload?.nil? %>
				<%= link_to reload_volume_path(@volume), class: 'btn btn-info' do %>
					<span data-toggle="tooltip" data-container="body" title="Manually reload this volume from its snapshot">Reload</span>
				<% end %>
			<% else %>
				<span class="btn btn-info disabled" data-toggle="tooltip" data-container="body" title="<%= @volume.reload? %>">Reload</span>
			<% end %>
		</span>
		<span class="info-box pull-right">
			<%= link_to 'Delete', volume_path(@volume), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this volume forever? (A really long time!)' } %>
		</span>
		<br />
		<br />
		<%= panel_with_heading 'Information' do %>
			<ul>
				<li>
					Suspending a volume will create a snapshot (backup) and delete the volume.
					Digital Ocean charges less for snapshots,
					but the volume must be reloaded before it can be used.
				</li>
				<li>
					If a server with a suspended volume is started, Gamocosm will automatically reload the volume for you.
				</li>
				<li>
					Attaching a volume to an existing server is not recommended unless you know what you are doing.
				</li>
				<li>
					Read more on the <%= link_to 'wiki', wiki_url('Using-Digital-Ocean-Volumes') %>.
				</li>
			</ul>
		<% end %>
	</div>
</div>

app/views/volumes/show_digital_ocean_snapshots.html.erb
<tbody>
	<% if @do_snapshots.nil? %>
		<tr><td><em>You haven't entered your Digital Ocean API token</em></td></tr>
	<% elsif @do_snapshots.error? %>
		<tr><td><em>Unable to get Digital Ocean snapshots: <%= @do_snapshots %></em></td></tr>
	<% elsif @do_snapshots.empty? %>
		<tr><td><em>You have no snapshots on Digital Ocean</em></td></tr>
	<% else %>
		<tr>
			<th>Name</th>
			<th class="text-right">ID</th>
			<th>&nbsp;</th>
		</tr>
		<% @do_snapshots.each do |x| %>
			<tr>
				<td><%= x.name %> (<%= x.created_at.to_datetime.in_time_zone(Gamocosm::TIME_ZONE).strftime('%Y %b %-d %H:%M %Z') %>)</td>
				<td class="text-right"><%= x.id %></td>
				<td>
					<%= link_to 'Delete', destroy_digital_ocean_snapshot_path(id: x.id), method: :delete, class: 'btn btn-default pull-right', data: { confirm: 'Are you sure you want to delete this snapshot forever? (A really long time!)' } %>
				</td>
			</tr>
		<% end %>
	<% end %>
</tbody>

app/views/volumes/show_digital_ocean_volumes.html.erb
<tbody>
	<% if @do_volumes.nil? %>
		<tr><td><em>You haven't entered your Digital Ocean API token</em></td></tr>
	<% elsif @do_volumes.error? %>
		<tr><td><em>Unable to get Digital Ocean volumes: <%= @do_volumes %></em></td></tr>
	<% elsif @do_volumes.empty? %>
		<tr><td><em>You have no volumes on Digital Ocean</em></td></tr>
	<% else %>
		<tr>
			<th>Name</th>
			<th class="text-right">ID</th>
			<th>&nbsp;</th>
		</tr>
		<% @do_volumes.each do |x| %>
			<tr>
				<td><%= x.name %> (<%= x.created_at.to_datetime.in_time_zone(Gamocosm::TIME_ZONE).strftime('%Y %b %-d %H:%M %Z') %>)</td>
				<td class="text-right"><%= x.id %></td>
				<td>
					<%= link_to 'Delete', destroy_digital_ocean_volume_path(id: x.id), method: :delete, class: 'btn btn-default pull-right', data: { confirm: 'Are you sure you want to delete this volume forever? (A really long time!)' } %>
				</td>
			</tr>
		<% end %>
	<% end %>
</tbody>