config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'pages#landing'

  get 'about', to: 'pages#about', as: :about
  get 'tos', to: 'pages#tos', as: :tos

  get 'badness/:secret', to: 'pages#badness'

  direct :git_head do
    "https://github.com/Gamocosm/Gamocosm/tree/#{Gamocosm::GIT_HEAD}"
  end

  direct :blog do
    'https://gamocosm.com/blog/'
  end

  direct :wiki do |page|
    if page.blank?
      'https://github.com/Gamocosm/Gamocosm/wiki'
    else
      "https://github.com/Gamocosm/Gamocosm/wiki/#{page}"
    end
  end

  direct :issues do
    'https://github.com/Gamocosm/Gamocosm/issues'
  end

  direct :source do
    'https://github.com/Gamocosm/Gamocosm'
  end

  direct :license do
    'https://github.com/Gamocosm/Gamocosm/blob/master/LICENSE'
  end

  direct :cuberite_website do
    'https://cuberite.org'
  end

  direct :gitter_lobby do
    'https://gitter.im/gamocosm/Lobby'
  end

  direct :digital_ocean_control_panel do
    'https://cloud.digitalocean.com'
  end

  direct :digital_ocean_status do
    'https://status.digitalocean.com'
  end

  direct :digital_ocean_api_setup do
    'https://docs.digitalocean.com/reference/api/create-personal-access-token/'
  end

  namespace :digital_ocean do
    resources :droplets, only: [:index, :destroy]

    resources :images, only: [:index, :destroy]

    resources :ssh_keys, only: [:index, :create, :destroy]

    resources :volumes, only: [:index, :destroy]

    resources :snapshots, only: [:index, :destroy]

    delete 'cache', to: '/servers#refresh_digital_ocean_cache', as: :refresh_cache
  end

  get 'servers/new', to: 'servers#new', as: :new_server
  post 'servers/new', to: 'servers#create', as: nil
  resources :servers, only: [:index, :show, :update, :destroy] do
    member do
      get 'confirm_delete'

      post 'start'
      post 'stop'
      post 'reboot'

      post 'pause'
      post 'resume'
      post 'command'
      post 'backup'
      get 'download'

      put 'update_properties'

      post 'add_friend'
      post 'remove_friend'

      post 'autoshutdown_enable'
      post 'autoshutdown_disable'

      delete 'clear_logs'

      scope path: 'api/:key', as: :api, controller: :api do
        get 'status'
        post 'start'
        post 'stop'
        post 'reboot'
        post 'pause'
        post 'resume'
        post 'backup'
        post 'exec'
      end
    end
  end

  resources :volumes, only: [:index, :new, :show, :edit, :create, :update, :destroy] do
    member do
      get 'confirm_delete'
      post 'suspend'
      post 'reload'
    end
  end

  devise_for :users, controllers: { registrations: :registrations }

  if Rails.env.production?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV['SIDEKIQ_USERNAME'])) &
        ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV['SIDEKIQ_PASSWORD']))
    end
  end
  mount Sidekiq::Web => '/sidekiq'

  match '*unused', to: 'pages#not_found', via: :all

end

app/views/layouts/components/_flash.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="flash-container row">
      <div class="alert alert-dismissable alert-<%= if name == 'error' then 'danger' elsif name == 'notice' then 'info' elsif name == 'alert' then 'warning' else name end %>">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= msg %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/components/_footer.html.erb
<footer id="footer">
	<div class="container">
		<div class="row">
			<div class="col-sm-3 text-muted">
				<ul>
					<li><b><%= link_to 'Home', root_url %></b></li>
					<li><%= link_to 'About', about_path %></li>
					<li><%= link_to 'Wiki', wiki_url %></li>
					<li><%= link_to 'Blog and Updates', blog_url %></li>
				</ul>
			</div>
			<div class="col-sm-3 text-muted">
				<ul>
					<li><b>Contact</b></li>
					<li><%= link_to 'GitHub Issues', issues_url %></li>
					<li><%= link_to 'Gitter Chat', gitter_lobby_url %></li>
				</ul>
			</div>
			<div class="col-sm-3 text-muted">
				<ul>
					<li><b><%= render_digital_ocean_referral_link('%s (%s)', 'Digital Ocean') %></b></li>
					<li><%= render_digital_ocean_referral_link('%s (%s)', 'Pricing', 'https://www.digitalocean.com/pricing/') %></li>
					<li><%= link_to 'Control Panel', digital_ocean_control_panel_url %></li>
					<li><%= link_to 'Status', digital_ocean_status_url %></li>
				</ul>
			</div>
			<div class="col-sm-3 text-muted">
				<ul>
					<li><b>Miscellaneous</b></li>
					<li><%= link_to 'Source Code', source_url %></li>
					<li><%= link_to 'Terms of Service', tos_path %></li>
					<li><%= modal_trigger 'Cookies and Data', 'gamocosm-cookies-and-data' %></li>
				</ul>
			</div>
		</div>
		<br />
		<div class="row">
			<div class="col-sm-12">
				<p class="copyright text-muted small">
					Design by <a href="https://mingard.link">Jono Mingard</a>.
					<br />
					Server running commit <%= link_to Gamocosm::GIT_HEAD, git_head_url %> from <%= Gamocosm::GIT_HEAD_DATE %>.
					<br />
					Copyright Gamocosm 2014 - <%= Date.today.year %>. All Rights Reserved.
				</p>
			</div>
		</div>
	</div>
</footer>
<%= modal_dialog 'Cookies and Data on Gamocosm', 'gamocosm-cookies-and-data' do %>
	<ul>
		<li>Gamocosm uses cookies only when strictly necessary (e.g. for remembering login status).</li>
		<li>Gamocosm does not do any tracking, analytics, marketing, etc.</li>
		<li>If you delete your account in <%= link_to 'your settings', edit_user_registration_path %>, all your Gamocosm data is permanently deleted.</li>
	</ul>
<% end %>

app/views/layouts/components/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-0">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to root_url, class: 'navbar-brand' do %>
				<%= inline_svg 'logo.svg' %> Gamocosm
			<% end %>
		</div>
		<div class="collapse navbar-collapse" id="navbar-collapse-0">
			<ul class="nav navbar-nav">
				<li><%= link_to 'About', about_path %></li>
				<li><%= link_to 'Wiki', wiki_url %></li>
				<li><%= link_to 'Blog and Updates', blog_url %></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<% if begin user_signed_in? rescue false end %>
					<li><%= link_to 'Servers', servers_path %></li>
					<li><%= link_to 'Volumes', volumes_path %></li>
					<li><%= link_to 'Settings', edit_user_registration_path %></li>
					<li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
				<% else %>
					<li><%= link_to 'Sign up', new_user_registration_path %></li>
					<li><%= link_to 'Login', new_user_session_path %></li>
				<% end %>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/components/_waiting_confirmation.html.erb
<% if resource.pending_reconfirmation? %>
	<div class="alert alert-warning">
		Currently waiting for confirmation for: <%= resource.unconfirmed_email %>.
		<%= link_to 'Resend email.', new_user_confirmation_path %>
		Note: until you confirm this email, you should still log in with <%= resource.email %>.
	</div>
<% elsif !resource.confirmed? %>
	<div class="alert alert-warning">
		Currently waiting for confirmation for: <%= resource.email %>.
		<%= link_to 'Resend email.', new_user_confirmation_path %>
	</div>
<% end %>